### ISSUE TITLE
Error in service worker: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by yacine-bens** [mellowtel-inc/mellowtel-js#6]
Error message: `Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`

It happens each time a link is visited or the page is refreshed. Just opening a new tab does not trigger it. Sometimes this one appears too: `Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received`

**Comment by yacine-bens** [comment]
Update: it is actually happening only when a new tab "blank" or "chrome://" tab is open.

**Comment by yacine-bens** [comment]
It's coming from `shared-memory.ts`. I fixed it locally. I'll create a PR.

**Comment by mellowtel** [comment]
Thanks for looking into this @yacine-bens! Makes a lot of sense, going to merge now
